name: Run Script

on:
  schedule:
    # This will run at 4:30 AM UTC (10:00 AM IST) every Sunday
    - cron: "30 4 * * 0"
    # This will run at 4:30 PM UTC (10:00 PM IST) every Saturday
    - cron: "30 16 * * 6"
  workflow_dispatch: # Allows manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install
        
      - name: Print environment variables
        run: env

      - name: Test environment
        run: |
          echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}"
          echo "SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}"
      - name: Run script
        env:
          POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          TZ: "Asia/Kolkata"

        run: node index.js
